apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentops-api
  namespace: agentops
  labels:
    app.kubernetes.io/name: agentops-reliability-platform
    app.kubernetes.io/component: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - agentops.example.com
      secretName: agentops-tls
  rules:
    - host: agentops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentops-api
                port:
                  name: http
