"""
Report formatters for production readiness assessments.

Generates JSON (programmatic consumption), Markdown (human-readable
reports and GitHub), and HTML (dashboard embedding) formats.
"""

from __future__ import annotations

import json
from typing import Any

from agentops.readiness.state import ReadinessReport, ReadinessTier


def format_readiness_json(report: ReadinessReport, indent: int = 2) -> str:
    """Format a readiness report as JSON."""
    return json.dumps(report.to_dict(), indent=indent)


def format_readiness_markdown(report: ReadinessReport) -> str:
    """Format a readiness report as Markdown for human consumption."""
    lines: list[str] = []

    # Header
    tier_emoji = {
        ReadinessTier.PRODUCTION_READY: "✅",
        ReadinessTier.CONDITIONAL: "⚠️",
        ReadinessTier.NEEDS_WORK: "🔧",
        ReadinessTier.CRITICAL_ISSUES: "🚨",
    }
    emoji = tier_emoji.get(report.tier, "❓")

    lines.append(f"# {emoji} Production Readiness Assessment")
    lines.append(f"**Agent:** {report.agent_name} v{report.agent_version}")
    lines.append(f"**Assessed:** {report.run_timestamp}")
    lines.append(f"**Duration:** {report.assessment_duration_ms:.0f}ms")
    lines.append("")

    # Tier badge
    lines.append(f"## Verdict: {report.tier.label}")
    lines.append(f"**Composite Score:** {report.composite_score:.1f}/100")
    lines.append(
        f"**Deployable:** {'Yes' if report.is_deployable else 'NO — fix issues first'}"
    )
    lines.append(f"**CI Exit Code:** {report.tier.exit_code}")
    lines.append("")

    # Dimension scores table
    lines.append("## Dimension Scores")
    lines.append("")
    lines.append(
        "| Dimension | Score | Status | Weight | Evidence |"
    )
    lines.append(
        "|-----------|-------|--------|--------|----------|"
    )

    status_icons = {"pass": "🟢", "warn": "🟡", "fail": "🔴"}
    for ds in report.dimension_scores:
        icon = status_icons.get(ds.status, "⚪")
        evidence = "; ".join(ds.evidence[:2])  # First 2 evidence items
        lines.append(
            f"| {ds.dimension.label} | {ds.score:.1f} | {icon} {ds.status.upper()} "
            f"| {ds.dimension.weight:.0%} | {evidence} |"
        )
    lines.append("")

    # Summary counts
    lines.append(f"**Pass:** {report.pass_count} | **Warn:** {report.warn_count} | **Fail:** {report.fail_count}")
    lines.append(f"**Benchmarks:** {report.total_benchmarks_run} | **Traces:** {report.total_traces_analyzed}")
    lines.append("")

    # Critical findings
    if report.critical_findings:
        lines.append("## Critical Findings")
        lines.append("")
        for finding in report.critical_findings:
            lines.append(f"- {finding}")
        lines.append("")

    # Recommendations
    if report.recommendations:
        lines.append("## Recommendations")
        lines.append("")
        for rec in report.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    # Dimension details
    lines.append("## Dimension Details")
    lines.append("")
    for ds in report.dimension_scores:
        icon = status_icons.get(ds.status, "⚪")
        lines.append(f"### {icon} {ds.dimension.label} — {ds.score:.1f}/100 ({ds.status.upper()})")
        lines.append("")
        lines.append(f"**Weight:** {ds.dimension.weight:.0%}")
        lines.append("")
        lines.append("**Evidence:**")
        for e in ds.evidence:
            lines.append(f"- {e}")
        lines.append("")
        lines.append(f"**Benchmarks used:** {', '.join(ds.benchmarks_used)}")
        lines.append("")
        if ds.recommendation:
            lines.append(f"**Recommendation:** {ds.recommendation}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        f"*Generated by AgentOps Reliability Platform v{report.agent_version} "
        f"— Production Readiness Assessment*"
    )

    return "\n".join(lines)


def format_readiness_html(report: ReadinessReport) -> str:
    """Format a readiness report as a self-contained HTML page for dashboards."""

    status_colors = {"pass": "#22c55e", "warn": "#eab308", "fail": "#ef4444"}
    tier_colors = {
        ReadinessTier.PRODUCTION_READY: "#22c55e",
        ReadinessTier.CONDITIONAL: "#eab308",
        ReadinessTier.NEEDS_WORK: "#f97316",
        ReadinessTier.CRITICAL_ISSUES: "#ef4444",
    }

    dim_rows = []
    for ds in report.dimension_scores:
        color = status_colors.get(ds.status, "#6b7280")
        evidence = "<br>".join(ds.evidence[:2])
        dim_rows.append(f"""
        <tr>
            <td>{ds.dimension.label}</td>
            <td style="color:{color}; font-weight:bold">{ds.score:.1f}</td>
            <td style="color:{color}">{ds.status.upper()}</td>
            <td>{ds.dimension.weight:.0%}</td>
            <td style="font-size:0.85em">{evidence}</td>
        </tr>""")

    crit_items = "".join(f"<li>{f}</li>" for f in report.critical_findings)
    rec_items = "".join(f"<li>{r}</li>" for r in report.recommendations)

    tier_color = tier_colors.get(report.tier, "#6b7280")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AgentOps Readiness — {report.agent_name}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background:#0f172a; color:#e2e8f0; padding:2rem }}
.container {{ max-width:960px; margin:0 auto }}
.header {{ text-align:center; margin-bottom:2rem }}
.verdict {{ font-size:1.5rem; font-weight:bold; padding:1rem; border-radius:8px;
           background:#1e293b; margin:1rem 0; border-left:4px solid {tier_color} }}
.composite {{ font-size:3rem; font-weight:bold; color:{tier_color}; text-align:center;
              margin:1rem 0 }}
table {{ width:100%; border-collapse:collapse; margin:1rem 0; background:#1e293b;
        border-radius:8px; overflow:hidden }}
th {{ background:#334155; padding:0.75rem; text-align:left; font-weight:600 }}
td {{ padding:0.75rem; border-top:1px solid #334155 }}
h2 {{ margin:2rem 0 1rem; color:#94a3b8 }}
h3 {{ margin:1.5rem 0 0.5rem }}
ul {{ margin-left:1.5rem; line-height:1.6 }}
.footer {{ margin-top:3rem; text-align:center; color:#64748b; font-size:0.85rem }}
.badge {{ display:inline-block; padding:0.25rem 0.75rem; border-radius:999px;
         font-size:0.75rem; font-weight:700 }}
.badge-pass {{ background:#22c55e33; color:#22c55e }}
.badge-warn {{ background:#eab30833; color:#eab308 }}
.badge-fail {{ background:#ef444433; color:#ef4444 }}
</style>
</head>
<body>
<div class="container">
<div class="header">
<h1>Production Readiness Assessment</h1>
<p>{report.agent_name} v{report.agent_version} — {report.run_timestamp}</p>
</div>

<div class="verdict">
{report.tier.label}
</div>

<div class="composite">{report.composite_score:.1f}<span style="font-size:1rem">/100</span></div>

<p style="text-align:center">
<span class="badge badge-pass">Pass: {report.pass_count}</span>
<span class="badge badge-warn">Warn: {report.warn_count}</span>
<span class="badge badge-fail">Fail: {report.fail_count}</span>
&nbsp;|&nbsp; Benchmarks: {report.total_benchmarks_run} | Traces: {report.total_traces_analyzed}
</p>

<h2>Dimension Scores</h2>
<table>
<thead><tr>
<th>Dimension</th><th>Score</th><th>Status</th><th>Weight</th><th>Evidence</th>
</tr></thead>
<tbody>
{"".join(dim_rows)}
</tbody>
</table>

<h2>Critical Findings</h2>
<ul>{crit_items}</ul>

<h2>Recommendations</h2>
<ul>{rec_items}</ul>

<div class="footer">
Generated by AgentOps Reliability Platform v{report.agent_version} — Production Readiness Assessment
</div>
</div>
</body>
</html>"""
